### ISSUE TITLE
Bicep template for Azure ASP.NET web application, Azure SQL DB and Private Link?

### ISSUE THREAD

**Issue by dmiyamasu** [ElYusubov/AWESOME-Azure-Bicep#39]
I was wondering if there is an Bicep sample for provisioning an Azure App Service, Azure SQL server, VNet and Private Endpoint?

**Comment by ElYusubov** [comment]
Hej @dmiyamasu , I have samples of Bicep codes in the repo: https://github.com/ElYusubov/Learn-Bicep
Check it out and look into:
App Services: https://github.com/ElYusubov/Learn-Bicep/blob/main/modules/appservice.bicep
Azure SQL: https://github.com/ElYusubov/Learn-Bicep/blob/main/modules/sqldb.bicep
Has VNet deployment samples in it: https://github.com/ElYusubov/Learn-Bicep/blob/main/modules/vm-win.bicep

You could use those Bicep codes as sample modules and bring them together too :)

For other samples, check the Bicep Playground site : https://bicepdemo.z22.web.core.windows.net/
Hope this will help you!
